version: '3'

services:
  jumpserver-core:
    image: "${JUMPSERVER_CORE_DOCKER_TAG:-vkill/jumpserver-core:1.4.4-alpine}"
    depends_on:
      - jumpserver-core-database
      - jumpserver-core-redis
    environment:
      SECRET_KEY: ${JUMPSERVER_CORE_SECRET_KEY:-your_secret_key}
      DB_ENGINE: ${JUMPSERVER_CORE_DB_ENGINE:-postgresql}
      DB_HOST: ${JUMPSERVER_CORE_DB_HOST:-jumpserver-database}
      DB_PORT: ${JUMPSERVER_CORE_DB_PORT:-5432}
      DB_NAME: ${JUMPSERVER_CORE_DB_DATABASE:-jumpserver}
      DB_USER: ${JUMPSERVER_CORE_DB_USER:-jumpserver}
      DB_PASSWORD: ${JUMPSERVER_CORE_DB_PASSWORD:-jumpserver}
      REDIS_HOST: ${JUMPSERVER_CORE_REDIS_HOST:-jumpserver-redis}
      REDIS_PORT: ${JUMPSERVER_CORE_REDIS_PORT:-6379}
    volumes:
      - jumpserver_core_data:/opt/jumpserver_core/data
    restart: always
    pid: host
    networks:
      - jumpserver

  jumpserver-core-database:
    image: "${JUMPSERVER_CORE_DATABASE_DOCKER_TAG:-postgres:11.1-alpine}"
    volumes:
      - jumpserver_core_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${JUMPSERVER_CORE_DB_DATABASE:-jumpserver}
      POSTGRES_USER: ${JUMPSERVER_CORE_DB_USER:-jumpserver}
      POSTGRES_PASSWORD: ${JUMPSERVER_CORE_DB_PASSWORD:-jumpserver}
      PGDATA: /var/lib/postgresql/data/db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${JUMPSERVER_CORE_DB_USER:-jumpserver}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    pid: host
    networks:
      - jumpserver

  jumpserver-core-redis:
    image: "${JUMPSERVER_CORE_REDIS_DOCKER_TAG:-redis:5.0-alpine}"
    volumes:
      - jumpserver_core_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    pid: host
    networks:
      - jumpserver

  jumpserver-coco:
    image: "${JUMPSERVER_COCO_DOCKER_TAG:-vkill/jumpserver-coco:1.4.4-alpine}"
    environment:
      SECRET_KEY: ${JUMPSERVER_COCO_SECRET_KEY:-your_secret_key}
      CORE_HOST: ${JUMPSERVER_COCO_CORE_HOST:-http://jumpserver-core:8080}
      ACCESS_KEY: ${JUMPSERVER_COCO_ACCESS_KEY:-your_access_key_id:your_access_key_secret}
    volumes:
      - jumpserver_coco_session:/opt/jumpserver_coco/sessions
    restart: always
    pid: host
    ports:
      - "${JUMPSERVER_COCO_SSHD_PORT:-2222}:2222/tcp"
    networks:
      - jumpserver

  jumpserver-luna:
    image: "${JUMPSERVER_LUNA_DOCKER_TAG:-vkill/jumpserver-luna:1.4.4-alpine}"
    restart: always
    pid: host
    networks:
      - jumpserver

  jumpserver-frontend:
    image: "${JUMPSERVER_FRONTEND_DOCKER_TAG:-vkill/jumpserver-frontend:alpine}"
    environment:
      CORE_HOST: ${JUMPSERVER_FRONTEND_CORE_HOST:-jumpserver-core}
      CORE_PORT: ${JUMPSERVER_FRONTEND_CORE_PORT:-8080}
      COCO_HOST: ${JUMPSERVER_FRONTEND_COCO_HOST:-jumpserver-coco}
      COCO_HTTPD_PORT: ${JUMPSERVER_FRONTEND_COCO_HTTPD_PORT:-5000}
      LUNA_HOST: ${JUMPSERVER_FRONTEND_LUNA_HOST:-jumpserver-luna}
      LUNA_PORT: ${JUMPSERVER_FRONTEND_LUNA_PORT:-80}
    volumes:
      - jumpserver_core_data:/opt/jumpserver_core/data
    restart: always
    pid: host
    ports:
      - "${JUMPSERVER_FRONTEND_PORT:-80}:80/tcp"
    networks:
      - jumpserver

volumes:
  jumpserver_core_data:
  jumpserver_core_postgres_data:
  jumpserver_core_redis_data:
  jumpserver_coco_session:

networks:
  jumpserver:
