version: '3'

services:
  jumpserver:
    image: "${JUMPSERVER_DOCKER_TAG:-vkill/jumpserver:1.4.4-alpine}"
    depends_on:
      - jumpserver-database
    environment:
      SECRET_KEY: ${JUMPSERVER_SECRET_KEY:-your_secret_key}
      DB_ENGINE: ${JUMPSERVER_DB_ENGINE:-postgres}
      DB_HOST: ${JUMPSERVER_DB_HOST:-jumpserver-database}
      DB_PORT: ${JUMPSERVER_DB_PORT:-5432}
      DB_NAME: ${JUMPSERVER_DB_DATABASE:-jumpserver}
      DB_USER: ${JUMPSERVER_DB_USER:-jumpserver}
      DB_PASSWORD: ${JUMPSERVER_DB_PASSWORD:-jumpserver}
      REDIS_HOST: ${JUMPSERVER_DB_HOST:-jumpserver-redis}
      REDIS_PORT: ${JUMPSERVER_DB_HOST:-6379}
    restart: always
    pid: host
    ports:
      - "${JUMPSERVER_PROXY_PORT:-80}:8000/tcp"
      - "${JUMPSERVER_PROXY_SSL_PORT:-443}:8443/tcp"
      - "${JUMPSERVER_ADMIN_PORT:-8001}:8001/tcp"
      - "${JUMPSERVER_ADMIN_SSL_PORT:-8444}:8444/tcp"
    networks:
      - jumpserver

  jumpserver-database:
    image: "${JUMPSERVER_DATABASE_DOCKER_TAG:-postgres:11.1-alpine}"
    volumes:
      - jumpserver_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${JUMPSERVER_DB_DATABASE:-jumpserver}
      POSTGRES_USER: ${JUMPSERVER_DB_USER:-jumpserver}
      POSTGRES_PASSWORD: ${JUMPSERVER_DB_PASSWORD:-jumpserver}
      PGDATA: /var/lib/postgresql/data/db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${JUMPSERVER_DB_USER:-jumpserver}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    pid: host
    networks:
      - jumpserver

  jumpserver-redis:
    image: "${JUMPSERVER_REDIS_DOCKER_TAG:-redis:5.0-alpine}"
    volumes:
      - jumpserver_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    pid: host
    networks:
      - jumpserver

volumes:
  jumpserver_postgres_data:
  jumpserver_redis_data:

networks:
  jumpserver:
