version: '3'

services:
  jumpserver-core:
    volumes:
      - jumpserver_core_log:/opt/jumpserver_core/logs

  jumpserver-core-database:
    command: postgres -c 'config_file=/var/lib/postgresql/data/postgresql.conf' #-c 'log_statement=all'
    volumes:
      - jumpserver_core_postgres_log:/var/log/postgresql

  jumpserver-coco:
    volumes:
      - jumpserver_coco_log:/opt/jumpserver_coco/logs

volumes:
  jumpserver_core_log:
    driver: local
    driver_opts:
      type: none
      device: ${JUMPSERVER_CORE_LOG:-/data/data_jumpserver/jumpserver_core_log}
      o: bind
  jumpserver_core_postgres_log:
    driver: local
    driver_opts:
      type: none
      device: ${JUMPSERVER_CORE_POSTGRES_LOG:-/data/data_jumpserver/jumpserver_core_postgres_log}
      o: bind
  jumpserver_coco_log:
    driver: local
    driver_opts:
      type: none
      device: ${JUMPSERVER_COCO_LOG:-/data/data_jumpserver/jumpserver_coco_log}
      o: bind
  jumpserver_core_data:
    driver: local
    driver_opts:
      type: none
      device: ${JUMPSERVER_COCO_DATA:-/data/data_jumpserver/jumpserver_core_data}
      o: bind
  jumpserver_core_postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${JUMPSERVER_CORE_POSTGRES_DATA:-/data/data_jumpserver/jumpserver_core_postgres_data}
      o: bind
  jumpserver_core_redis_data:
    driver: local
    driver_opts:
      type: none
      device: ${JUMPSERVER_CORE_REDIS_DATA:-/data/data_jumpserver/jumpserver_core_redis_data}
      o: bind
  jumpserver_coco_session:
    driver: local
    driver_opts:
      type: none
      device: ${JUMPSERVER_COCO_SESSION:-/data/data_jumpserver/jumpserver_coco_session}
      o: bind
